#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ActivatableMovieWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActivatableMovieWidget.ActivatableMovieWidget_C
// 0x0008 (0x0370 - 0x0368)
class UActivatableMovieWidget_C final : public UFortActivatableVideoPanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ActivatableMovieWidget(int32 EntryPoint);
	void OnActivated();
	void OnDeactivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ActivatableMovieWidget_C">();
	}
	static class UActivatableMovieWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivatableMovieWidget_C>();
	}
};

}

