#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Pickups_Default

#include "Basic.hpp"

#include "B_Pickups_Parent_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Pickups_Default.B_Pickups_Default_C
// 0x0018 (0x05B0 - 0x0598)
class AB_Pickups_Default_C final : public AB_Pickups_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Pickups_Default_C;                // 0x0598(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USpotLightComponent*                    SpotLight;                                         // 0x05A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Background;                                        // 0x05A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Pickups_Default(int32 EntryPoint);
	void OnPickedUp();
	void OnTossed();
	void UserConstructionScript();
	void Setup_Light();
	void Set_Initial_BKGD_Param(class UMaterialInstanceDynamic* Mid);
	void Randomize_Mesh_Rotation_for_BR();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Pickups_Default_C">();
	}
	static class AB_Pickups_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Pickups_Default_C>();
	}
};

}

