#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CCStatsGameplayEffect

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CCStatsGameplayEffect.CCStatsGameplayEffect_C
// 0x0000 (0x05F0 - 0x05F0)
class UCCStatsGameplayEffect_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CCStatsGameplayEffect_C">();
	}
	static class UCCStatsGameplayEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCCStatsGameplayEffect_C>();
	}
};

}

