#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CollectionBookRecycleSlotResultsWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CollectionBookRecycleSlotResultsWidget.CollectionBookRecycleSlotResultsWidget_C
// 0x0010 (0x0258 - 0x0248)
class UCollectionBookRecycleSlotResultsWidget_C final : public UFortCollectionBookRecycleSlotResultsWidget
{
public:
	class UCommonTextBlock*                       DisplayNameWidget;                                 // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CollectionBookRecycleSlotResultsWidget_C">();
	}
	static class UCollectionBookRecycleSlotResultsWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCollectionBookRecycleSlotResultsWidget_C>();
	}
};

}

