#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CollectionBookSlotView

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CollectionBookSlotView.CollectionBookSlotView_C
// 0x0008 (0x02E0 - 0x02D8)
class UCollectionBookSlotView_C final : public UFortCollectionBookSlotView
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_CollectionBookSlotView(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CollectionBookSlotView_C">();
	}
	static class UCollectionBookSlotView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCollectionBookSlotView_C>();
	}
};

}

