#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CreativeSettingsPanel

#include "Basic.hpp"

#include "CreativeSettingsPanel_classes.hpp"
#include "CreativeSettingsPanel_parameters.hpp"


namespace SDK
{

// Function CreativeSettingsPanel.CreativeSettingsPanel_C.ExecuteUbergraph_CreativeSettingsPanel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCreativeSettingsPanel_C::ExecuteUbergraph_CreativeSettingsPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "ExecuteUbergraph_CreativeSettingsPanel");

	Params::CreativeSettingsPanel_C_ExecuteUbergraph_CreativeSettingsPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.Setup Tabs
// (BlueprintCallable, BlueprintEvent)

void UCreativeSettingsPanel_C::Setup_Tabs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "Setup Tabs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.BndEvt__Button_1_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCreativeSettingsPanel_C::BndEvt__Button_1_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "BndEvt__Button_1_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCreativeSettingsPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.BndEvt__UserActionMenuInputButton_0_K2Node_ComponentBoundEvent_8_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCreativeSettingsPanel_C::BndEvt__UserActionMenuInputButton_0_K2Node_ComponentBoundEvent_8_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "BndEvt__UserActionMenuInputButton_0_K2Node_ComponentBoundEvent_8_CommonButtonClicked__DelegateSignature");

	Params::CreativeSettingsPanel_C_BndEvt__UserActionMenuInputButton_0_K2Node_ComponentBoundEvent_8_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.OnInputModeChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bUsingGamepad                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCreativeSettingsPanel_C::OnInputModeChanged(bool bUsingGamepad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "OnInputModeChanged");

	Params::CreativeSettingsPanel_C_OnInputModeChanged Parms{};

	Parms.bUsingGamepad = bUsingGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.BndEvt__CancelButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCreativeSettingsPanel_C::BndEvt__CancelButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "BndEvt__CancelButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature");

	Params::CreativeSettingsPanel_C_BndEvt__CancelButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_5_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCreativeSettingsPanel_C::BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_5_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_5_CommonButtonClicked__DelegateSignature");

	Params::CreativeSettingsPanel_C_BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_5_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.CycleRight
// (BlueprintCallable, BlueprintEvent)

void UCreativeSettingsPanel_C::CycleRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "CycleRight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.CycleLeft
// (BlueprintCallable, BlueprintEvent)

void UCreativeSettingsPanel_C::CycleLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "CycleLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.Close
// (BlueprintCallable, BlueprintEvent)

void UCreativeSettingsPanel_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.OnActivated
// (Event, Protected, BlueprintEvent)

void UCreativeSettingsPanel_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.BndEvt__IconTextButton_C_0_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCreativeSettingsPanel_C::BndEvt__IconTextButton_C_0_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "BndEvt__IconTextButton_C_0_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature");

	Params::CreativeSettingsPanel_C_BndEvt__IconTextButton_C_0_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCreativeSettingsPanel_C::BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature");

	Params::CreativeSettingsPanel_C_BndEvt__IconTextButton_C_1_K2Node_ComponentBoundEvent_3_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.BndEvt__IconTextButton_C_2_K2Node_ComponentBoundEvent_4_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCreativeSettingsPanel_C::BndEvt__IconTextButton_C_2_K2Node_ComponentBoundEvent_4_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "BndEvt__IconTextButton_C_2_K2Node_ComponentBoundEvent_4_CommonButtonClicked__DelegateSignature");

	Params::CreativeSettingsPanel_C_BndEvt__IconTextButton_C_2_K2Node_ComponentBoundEvent_4_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.HandleClose
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCreativeSettingsPanel_C::HandleClose(bool* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "HandleClose");

	Params::CreativeSettingsPanel_C_HandleClose Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function CreativeSettingsPanel.CreativeSettingsPanel_C.Player in Read Only Volume?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bInReadOnlyVolume                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCreativeSettingsPanel_C::Player_in_Read_Only_Volume_(bool* bInReadOnlyVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CreativeSettingsPanel_C", "Player in Read Only Volume?");

	Params::CreativeSettingsPanel_C_Player_in_Read_Only_Volume_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bInReadOnlyVolume != nullptr)
		*bInReadOnlyVolume = Parms.bInReadOnlyVolume;
}

}

