#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: DefenderLimitDisplay

#include "Basic.hpp"

#include "DefenderLimitDisplay_classes.hpp"
#include "DefenderLimitDisplay_parameters.hpp"


namespace SDK
{

// Function DefenderLimitDisplay.DefenderLimitDisplay_C.ExecuteUbergraph_DefenderLimitDisplay
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDefenderLimitDisplay_C::ExecuteUbergraph_DefenderLimitDisplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefenderLimitDisplay_C", "ExecuteUbergraph_DefenderLimitDisplay");

	Params::DefenderLimitDisplay_C_ExecuteUbergraph_DefenderLimitDisplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DefenderLimitDisplay.DefenderLimitDisplay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UDefenderLimitDisplay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefenderLimitDisplay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefenderLimitDisplay.DefenderLimitDisplay_C.UpdateDefenderLimitCount
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UDefenderLimitDisplay_C::UpdateDefenderLimitCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefenderLimitDisplay_C", "UpdateDefenderLimitCount");

	UObject::ProcessEvent(Func, nullptr);
}

}

