#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: DefenderLimitDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DefenderLimitDisplay.DefenderLimitDisplay_C
// 0x0010 (0x0238 - 0x0228)
class UDefenderLimitDisplay_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       DefenderLimitText;                                 // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_DefenderLimitDisplay(int32 EntryPoint);
	void Construct();
	void UpdateDefenderLimitCount();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DefenderLimitDisplay_C">();
	}
	static class UDefenderLimitDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefenderLimitDisplay_C>();
	}
};

}

