#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GAB_FiendFloorMelee

#include "Basic.hpp"

#include "GAB_FiendMelee_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GAB_FiendFloorMelee.GAB_FiendFloorMelee_C
// 0x0000 (0x0970 - 0x0970)
class UGAB_FiendFloorMelee_C final : public UGAB_FiendMelee_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GAB_FiendFloorMelee_C">();
	}
	static class UGAB_FiendFloorMelee_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGAB_FiendFloorMelee_C>();
	}
};

}

