#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GCN_RiftSpawner_DMG_Stage_02_Loop

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_RiftSpawner_DMG_Stage_02_Loop.GCN_RiftSpawner_DMG_Stage_02_Loop_C
// 0x0000 (0x0880 - 0x0880)
class AGCN_RiftSpawner_DMG_Stage_02_Loop_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_RiftSpawner_DMG_Stage_02_Loop_C">();
	}
	static class AGCN_RiftSpawner_DMG_Stage_02_Loop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCN_RiftSpawner_DMG_Stage_02_Loop_C>();
	}
};

}

