#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Blade_InitialEquip

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Blade_InitialEquip.GE_Blade_InitialEquip_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Blade_InitialEquip_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Blade_InitialEquip_C">();
	}
	static class UGE_Blade_InitialEquip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Blade_InitialEquip_C>();
	}
};

}

