#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_DanceStun_ALSyne

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_DanceStun_ALSyne.GE_DanceStun_ALSyne_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_DanceStun_ALSyne_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_DanceStun_ALSyne_C">();
	}
	static class UGE_DanceStun_ALSyne_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_DanceStun_ALSyne_C>();
	}
};

}

