#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_FiendDamageBuff

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_FiendDamageBuff.GE_FiendDamageBuff_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_FiendDamageBuff_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_FiendDamageBuff_C">();
	}
	static class UGE_FiendDamageBuff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_FiendDamageBuff_C>();
	}
};

}

