#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_WeaknessAgainstExplosives

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_WeaknessAgainstExplosives.GE_WeaknessAgainstExplosives_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_WeaknessAgainstExplosives_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_WeaknessAgainstExplosives_C">();
	}
	static class UGE_WeaknessAgainstExplosives_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_WeaknessAgainstExplosives_C>();
	}
};

}

