#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GET_DamageMultiplier

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GET_DamageMultiplier.GET_DamageMultiplier_C
// 0x0000 (0x05F0 - 0x05F0)
class UGET_DamageMultiplier_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GET_DamageMultiplier_C">();
	}
	static class UGET_DamageMultiplier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGET_DamageMultiplier_C>();
	}
};

}

