#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ItemReceivedPCBChallenges

#include "Basic.hpp"


namespace SDK::Params
{

// Function ItemReceivedPCBChallenges.ItemReceivedPCBChallenges_C.ExecuteUbergraph_ItemReceivedPCBChallenges
// 0x0004 (0x0004 - 0x0000)
struct ItemReceivedPCBChallenges_C_ExecuteUbergraph_ItemReceivedPCBChallenges final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

