#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: LiveStreamVoice

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class LiveStreamVoice.LiveStreamVoiceChannel
// 0x0000 (0x0080 - 0x0080)
class ULiveStreamVoiceChannel final : public UVoiceChannel
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveStreamVoiceChannel">();
	}
	static class ULiveStreamVoiceChannel* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveStreamVoiceChannel>();
	}
};

}

