#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Minigame_PlayerCreated

#include "Basic.hpp"

#include "Minigame_PlayerCreated_classes.hpp"
#include "Minigame_PlayerCreated_parameters.hpp"


namespace SDK
{

// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.ExecuteUbergraph_Minigame_PlayerCreated
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMinigame_PlayerCreated_C::ExecuteUbergraph_Minigame_PlayerCreated(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "ExecuteUbergraph_Minigame_PlayerCreated");

	Params::Minigame_PlayerCreated_C_ExecuteUbergraph_Minigame_PlayerCreated Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.OnPlayerTeleportedForMinigameStart
// (Event, Protected, BlueprintEvent)
// Parameters:
// class APlayerState*                     PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bTeleportedToSky                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMinigame_PlayerCreated_C::OnPlayerTeleportedForMinigameStart(class APlayerState* PlayerState, bool bTeleportedToSky)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "OnPlayerTeleportedForMinigameStart");

	Params::Minigame_PlayerCreated_C_OnPlayerTeleportedForMinigameStart Parms{};

	Parms.PlayerState = PlayerState;
	Parms.bTeleportedToSky = bTeleportedToSky;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.HandleMinigameEnded
// (Event, Protected, BlueprintEvent)

void AMinigame_PlayerCreated_C::HandleMinigameEnded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "HandleMinigameEnded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.HandleMinigameStarted
// (Event, Protected, BlueprintEvent)

void AMinigame_PlayerCreated_C::HandleMinigameStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "HandleMinigameStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.HandleMinigameWarmup
// (Event, Protected, BlueprintEvent)

void AMinigame_PlayerCreated_C::HandleMinigameWarmup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "HandleMinigameWarmup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.OnPlayerRemoved
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMinigame_PlayerCreated_C::OnPlayerRemoved(class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "OnPlayerRemoved");

	Params::Minigame_PlayerCreated_C_OnPlayerRemoved Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.OnPlayerAdded
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMinigame_PlayerCreated_C::OnPlayerAdded(class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "OnPlayerAdded");

	Params::Minigame_PlayerCreated_C_OnPlayerAdded Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.PlayerTeleportedFX
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawnAthena*            PlayerPawn                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bToSky                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMinigame_PlayerCreated_C::PlayerTeleportedFX(class AFortPlayerPawnAthena* PlayerPawn, bool bToSky)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "PlayerTeleportedFX");

	Params::Minigame_PlayerCreated_C_PlayerTeleportedFX Parms{};

	Parms.PlayerPawn = PlayerPawn;
	Parms.bToSky = bToSky;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AMinigame_PlayerCreated_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.SetMusicActive
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShouldPlayMusic                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class APlayerState*                     PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMinigame_PlayerCreated_C::SetMusicActive(bool bShouldPlayMusic, class APlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "SetMusicActive");

	Params::Minigame_PlayerCreated_C_SetMusicActive Parms{};

	Parms.bShouldPlayMusic = bShouldPlayMusic;
	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Minigame_PlayerCreated.Minigame_PlayerCreated_C.AssignTeams
// (Public, BlueprintCallable, BlueprintEvent)

void AMinigame_PlayerCreated_C::AssignTeams()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Minigame_PlayerCreated_C", "AssignTeams");

	UObject::ProcessEvent(Func, nullptr);
}

}

