#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MinigameMode_PirateShip

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "Engine_structs.hpp"
#include "MinigameMode_Skirmish_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MinigameMode_PirateShip.MinigameMode_PirateShip_C
// 0x0028 (0x05F0 - 0x05C8)
class AMinigameMode_PirateShip_C final : public AMinigameMode_Skirmish_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_MinigameMode_PirateShip_C;          // 0x05C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UFortWorldItemDefinition*>       Pirate_Ship_Weapons;                               // 0x05D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<class UFortWorldItemDefinition*>       Pirate_Ship_Ammo;                                  // 0x05E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)

public:
	void ExecuteUbergraph_MinigameMode_PirateShip(int32 EntryPoint);
	void GiveStartingWeapon();
	void UserConstructionScript();
	struct FGameplayTagQuery GetStartQueryForPlayer(class APlayerState* Player);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MinigameMode_PirateShip_C">();
	}
	static class AMinigameMode_PirateShip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMinigameMode_PirateShip_C>();
	}
};

}

