#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MiniCraftingIngredientList

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass MiniCraftingIngredientList.MiniCraftingIngredientList_C
// 0x0010 (0x02C0 - 0x02B0)
class UMiniCraftingIngredientList_C final : public UFortItemQuantityListBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWrapBox*                               EntriesWrapBox;                                    // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MiniCraftingIngredientList(int32 EntryPoint);
	void AddListEntry(class UFortItemQuantityListEntryBase* ListEntry);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MiniCraftingIngredientList_C">();
	}
	static class UMiniCraftingIngredientList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMiniCraftingIngredientList_C>();
	}
};

}

