#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: MountedTurretConfigs

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MountedTurretConfigs.MountedTurretConfigs_C
// 0x0000 (0x0398 - 0x0398)
class UMountedTurretConfigs_C final : public UFortMountedTurretConfigs
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MountedTurretConfigs_C">();
	}
	static class UMountedTurretConfigs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMountedTurretConfigs_C>();
	}
};

}

