#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PartySlot

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PartySlot.PartySlot_C
// 0x0000 (0x0240 - 0x0240)
class UPartySlot_C final : public UFortPartySlot
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PartySlot_C">();
	}
	static class UPartySlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPartySlot_C>();
	}
};

}

