#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Prop_PlantPotted05

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prop_PlantPotted05.Prop_PlantPotted05_C
// 0x0000 (0x0CB0 - 0x0CB0)
class AProp_PlantPotted05_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Prop_PlantPotted05_C">();
	}
	static class AProp_PlantPotted05_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_PlantPotted05_C>();
	}
};

}

