#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Shelters_Buckets01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Shelters_Buckets01.Shelters_Buckets01_C
// 0x0000 (0x0CB0 - 0x0CB0)
class AShelters_Buckets01_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Shelters_Buckets01_C">();
	}
	static class AShelters_Buckets01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShelters_Buckets01_C>();
	}
};

}

