#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Sign_Exit_Leave

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Sign_Exit_Leave.Sign_Exit_Leave_C
// 0x0000 (0x0CB0 - 0x0CB0)
class ASign_Exit_Leave_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Sign_Exit_Leave_C">();
	}
	static class ASign_Exit_Leave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASign_Exit_Leave_C>();
	}
};

}

