#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SquadTilePopupMenuButtons

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum SquadTilePopupMenuButtons.SquadTilePopupMenuButtons
// NumValues: 0x0007
enum class ESquadTilePopupMenuButtons : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator5                           = 4,
	NewEnumerator4                           = 5,
	SquadTilePopupMenuButtons_MAX            = 6,
};

}

