#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: TeamScorePanelContent

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TeamScorePanelContent.TeamScorePanelContent_C
// 0x0008 (0x0238 - 0x0230)
class UTeamScorePanelContent_C final : public UCommonUserWidget
{
public:
	class UTeamScoreDetailsContent_C*             TeamScoreDetailsContent;                           // 0x0230(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TeamScorePanelContent_C">();
	}
	static class UTeamScorePanelContent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamScorePanelContent_C>();
	}
};

}

